language: python
python:
  - "2.7"
#install:
#  - pip install -r requirements.txt
script:
#  - pytest # or py.test for Python versions 3.5 and below
  - export RESULTS_BASE_DIR=dst
  - chmod +x run-unittests.sh
  - ./run-unittests.sh
