language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y exuberant-ctags
#install:
#  - pip install -r requirements.txt
script:
  - export RESULTS_BASE_DIR=dst
  - chmod +x run-unittests.sh
  - ./run-unittests.sh
