language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y exuberant-ctags libsvn-dev graphviz
install:
  - chmod +x install_requirements.sh
  - ./install_requirements.sh
script:
  - export RESULTS_BASE_DIR=dst
  - chmod +x run-unittests.sh
  - ./run-unittests.sh
#TODO uncomment when tests are running stable initially
#after_success:
  - codecov
