language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y exuberant-ctags libsvn-dev graphviz
install:
  - chmod +x install_requirements.sh
  - ./install_requirements.sh
  - chmod +x build_external.sh
  - ./build_external.sh
script:
  - export RESULTS_BASE_DIR=dst
  - export CDEP_PROGRAM=$(pwd)/external/idep/bin/cdep
  - chmod +x run-tests.sh
  - ./run-tests.sh

